Most : 
1. System that can track the equipments lent. 
2. Be able to detremine whether the equipments stored or lent out. 
3. Be able to identify who is the person that the equipment lent to and provide an email. 
4. items can be removed or added. 
2. items are catagorized. 
1. system has a search method to make it easier to find items. 
2. items are catagorized. 
3. system has a sign up system. 
4. adding a catagoorize 
