# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Users.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class User(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 309)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Tabl_U = QtWidgets.QTableWidget(Dialog)
        self.Tabl_U.setGeometry(QtCore.QRect(30, 50, 531, 201))
        self.Tabl_U.setObjectName("Tabl_U")
        self.Tabl_U.setColumnCount(10)
        self.Tabl_U.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabl_U.setItem(0, 0, item)
        self.Revert_U = QtWidgets.QPushButton(Dialog)
        self.Revert_U.setGeometry(QtCore.QRect(290, 270, 131, 32))
        self.Revert_U.setStyleSheet("color: rgb(145, 30, 33);")
        self.Revert_U.setAutoDefault(True)
        self.Revert_U.setDefault(True)
        self.Revert_U.setFlat(False)
        self.Revert_U.setObjectName("Revert_U")
        self.Confirm_U = QtWidgets.QPushButton(Dialog)
        self.Confirm_U.setGeometry(QtCore.QRect(430, 270, 131, 32))
        self.Confirm_U.setStyleSheet("color: rgb(145, 30, 33);")
        self.Confirm_U.setAutoDefault(True)
        self.Confirm_U.setDefault(True)
        self.Confirm_U.setFlat(False)
        self.Confirm_U.setObjectName("Confirm_U")
        self.Back_U = QtWidgets.QPushButton(Dialog)
        self.Back_U.setGeometry(QtCore.QRect(10, 10, 61, 32))
        self.Back_U.setObjectName("Back_U")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "USERS"))
        item = self.Tabl_U.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Email"))
        item = self.Tabl_U.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Where"))
        item = self.Tabl_U.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "House"))
        item = self.Tabl_U.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "USER"))
        item = self.Tabl_U.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "USER"))
        item = self.Tabl_U.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "USER"))
        item = self.Tabl_U.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "USER"))
        item = self.Tabl_U.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "USER"))
        __sortingEnabled = self.Tabl_U.isSortingEnabled()
        self.Tabl_U.setSortingEnabled(False)
        self.Tabl_U.setSortingEnabled(__sortingEnabled)
        self.Revert_U.setText(_translate("Dialog", "Revert Changes"))
        self.Confirm_U.setText(_translate("Dialog", "Confirm Changes"))
        self.Back_U.setText(_translate("Dialog", "BACK"))
